theme: jekyll-theme-minimal
title: Lesley Zheng
logo: "/images/logo.png?raw=true"
description: 
A creator. An explorer. A computer scientist and mathematician.
<br><br>
I’m a rising senior at Amherst College currently pursuing a double major in Computer Science and Mathematics. I came into college intending to major in Math. I am passionate about Math because it challenges me to think abstractly, logically, and rigorously. Along the way, I fell in love with Computer Scientist. Computer Science fulfilled my desire to become a creator. It is a field that creates new innovative solutions in the process of its problem-solving.
<br><br>
<a href="https://www.linkedin.com/in/lesley-zheng-2021/">View My LinkedIn Profile</a>
google_analytics: UA-169257937-1
